### ISSUE TITLE
where are .surf files from?

### ISSUE THREAD

**Issue by JohnGriffiths** [NeuroanatomyAndConnectivity/gradient_analysis#8]
Notebook '03_visualize_embeddings.ipynb' uses a file called 
`gradient_data/templates/S900.L.midthickness_MSMAll.32k_fs_LR.surf`

Where does this file come from?

Closest I know of is from a folder called `HCP_S900_GroupAvg_v1.zip` that I obtained from a slightly random internet location, which contains file `S900.L.midthickness_MSMAll.32k_fs_LR.surf.gii`

Seems that mapping between freesurfer and HCP surface spaces is a little more involved than one might like. 

Do you have the commands used for this somewhere here?

Ta.

**Comment by margulies** [comment]
Those were created as a work around to enable importing of the surface geometry a while back. They were converted by using wb_command to convert the gifti format to ascii and then mris_convert to output the freesurfer format. I've uploaded the files to the directory. There's certainly a better way to read the .gii directly using nibabel now, but in the meantime, the .surf files are available...
