### ISSUE TITLE
Missing file - hcp.tmp.lh.dscalar.nii

### ISSUE THREAD

**Issue by JohnGriffiths** [NeuroanatomyAndConnectivity/gradient_analysis#9]
Hi again. 

Getting following error:
`nibabel.py3k.FileNotFoundError: No such file: 'gradient_data/templates/hcp.tmp.lh.dscalar.nii'`

where is this file supposed to come from?
Ta.

**Comment by margulies** [comment]
Thanks! Just added the tmp files for indexing purposes...
